/* NOSTROMO GUT v0.2.8 — deterministic auditable metabolic router */
(function(root){
const DESTINATIONS=['SHROOMING','MUTHER','DROPLET','VAJRA','HOLD'];
function flatten(value,out,path,provenance){out=out||[];path=path||'root';provenance=provenance||{};if(value===null||value===undefined){out.push({path,value:null,provenance});return out;}if(typeof value==='string'||typeof value==='number'||typeof value==='boolean'){out.push({path,value,provenance});return out;}if(Array.isArray(value)){value.forEach((v,i)=>flatten(v,out,`${path}[${i}]`,provenance));return out;}if(typeof value==='object'){const nextProv={...provenance};for(const k of ['source','executor','organ','action','status','url','sourceClass','fingerprint','sourceFingerprint','provenanceFingerprint'])if(value[k]!==undefined&&value[k]!==null)nextProv[k]=String(value[k]).slice(0,240);Object.keys(value).forEach(k=>flatten(value[k],out,`${path}.${k}`,nextProv));}return out;}
function textOf(atom){return String(atom.value??'').trim();}
function compact(s,n){return String(s??'').replace(/\s+/g,' ').trim().slice(0,n||1e9);}
function stripInherited(text,substrates){let out=compact(text),count=0;const candidates=[];for(const s of substrates||[]){const full=compact(s);if(full.length<48)continue;for(const v of [full,compact(full,1200),compact(full,180)])if(v.length>=48&&!candidates.includes(v))candidates.push(v);}candidates.sort((a,b)=>b.length-a.length);for(const c of candidates){while(out.includes(c)){out=out.replace(c,' ').replace(/\s{2,}/g,' ').trim();count++;}}return {text:out,count};}
function stripRouteTags(s){let count=0;const text=String(s).replace(/\[[A-Z_]+->[A-Z/]+\]/g,()=>{count++;return '';}).replace(/\s{2,}/g,' ').replace(/\s+([:：·])/g,'$1').trim();return {text,count};}
function collapseSegmentEcho(s){const tokens=String(s).split(/(\s*[：:]\s*)/);if(tokens.length<3)return {text:String(s),count:0};const out=[tokens[0]];let count=0,prev=compact(tokens[0]).toLowerCase();for(let i=1;i<tokens.length;i+=2){const delim=tokens[i]||'',part=tokens[i+1]||'',norm=compact(part).toLowerCase();if(norm.length>=32&&norm===prev){count++;continue;}out.push(delim,part);prev=norm;}return {text:out.join('').trim(),count};}
function collapseDelimitedEcho(s){const parts=String(s).split(/(\s*(?:·|[;；])\s*|\n+)/);if(parts.length<3)return {text:String(s),count:0};const out=[];const seen=new Set();let count=0;for(let i=0;i<parts.length;i+=2){const segment=parts[i]||'',delim=i>0?(parts[i-1]||' '):'',norm=compact(segment).toLowerCase();if(norm.length>=40&&seen.has(norm)){count++;continue;}if(norm.length>=40)seen.add(norm);if(out.length&&delim)out.push(delim);out.push(segment);}return {text:out.join('').replace(/\s{2,}/g,' ').trim(),count};}
function normalizeEcho(raw,substrates){const inherited=stripInherited(raw,substrates);const original=inherited.text;const ms=[...original.matchAll(/\[[A-Z_]+->[A-Z/]+\]/g)];const seen=new Set();let base=original,nested=false,nestedTag=null,nestedCount=0;for(const m of ms){if(seen.has(m[0])){base=original.slice(0,m.index).replace(/[\s:：·|>\-]+$/g,'').trim();nested=true;nestedTag=m[0];nestedCount=ms.filter(x=>x[0]===m[0]&&x.index>=m.index).length;break;}seen.add(m[0]);}const stripped=stripRouteTags(base);const collapsed=collapseSegmentEcho(stripped.text);const delimited=collapseDelimitedEcho(collapsed.text);return {text:delimited.text,inheritedSubstrateStripped:inherited.count,nestedSuppressed:nested,nestedTag,nestedCount,routeTagsStripped:stripped.count,segmentEchoSuppressed:collapsed.count,delimitedEchoSuppressed:delimited.count};}
function looksStructured(text){const s=String(text);const escaped=(s.match(/\\"/g)||[]).length;const jsonish=(s.match(/"[A-Za-z_][A-Za-z0-9_]*"\s*:/g)||[]).length;return escaped>=3||jsonish>=3||(/^\s*[\[{]/.test(s)&&/[}\]]\s*$/.test(s)&&s.length>80);}
function classify(atom,text){const lower=text.toLowerCase(),path=atom.path.toLowerCase();if(text.length<3||/^(none|—|-|null|undefined)$/i.test(text))return {type:'LOW_SIGNAL',status:'EXCRETE',route:'HOLD',priority:0,reason:'low-signal'};if(/failed|error|rejected|invalid|quarantine|untrusted/i.test(lower+path))return {type:'RISK_OR_FAILURE',status:'QUARANTINE',route:'HOLD',priority:5,reason:'failure-or-risk-marker'};if(looksStructured(text))return {type:'RAW_STRUCTURED_SNIPPET',status:'ROUTE',route:'MUTHER',priority:1,reason:'structured-artifact-not-semantic-claim'};if(/contradict|counterevidence|refut|conflict|disagree|反例|矛盾|衝突|反證/i.test(lower+path))return {type:'CONTRADICTION',status:'ROUTE',route:'VAJRA',priority:5,reason:'counterevidence-or-conflict'};if(/question|unresolved|why|how|what|誰|什麼|為何|如何|問題/i.test(lower+path)||/[?？]$/.test(text))return {type:'QUESTION',status:'ROUTE',route:'SHROOMING',priority:4,reason:'question-or-unresolved'};if(/claim|hypothesis|position|assert|finding|判斷|命題|假設|主張/i.test(lower+path))return {type:'CLAIM',status:'ROUTE',route:'DROPLET',priority:4,reason:'claim-needs-evidence'};if(/evidence|source|citation|provenance|statuscode|returnedcount|hitcount|證據|來源/i.test(lower+path))return {type:'EVIDENCE_OR_PROVENANCE',status:'ABSORB',route:'MUTHER',priority:4,reason:'evidence-or-provenance'};if(/uncertain|indeterminate|unknown|partial|ambiguous|不確定|未知|部分/i.test(lower+path))return {type:'UNCERTAINTY',status:'HOLD',route:'HOLD',priority:3,reason:'uncertainty-preserved'};if(/memory|history|previousround|carry|trace|round/i.test(lower+path))return {type:'HISTORY',status:'ABSORB',route:'SHROOMING',priority:2,reason:'history-or-memory'};if(/request|action|execute|task|directive|next/i.test(lower+path))return {type:'ACTION',status:'ROUTE',route:'MUTHER',priority:3,reason:'actionable-material'};return {type:'MATERIAL',status:'ABSORB',route:'HOLD',priority:1,reason:'general-material'};}
function echoKey(text){return String(text).toLowerCase().replace(/\s+/g,' ').slice(0,96);}
function selectDiverse(ranked,limit){const picked=[],seen=new Set();for(const item of ranked){const key=echoKey(item.text);if(key.length>=24&&seen.has(key))continue;if(key.length>=24)seen.add(key);picked.push(item);if(picked.length>=limit)break;}return picked;}
function digest(input,options){options=options||{};const source=options.source||'unknown',substrates=Array.isArray(options.inheritedSubstrates)?options.inheritedSubstrates:[];const atoms=flatten(input,[],'root',{inputSource:source}).filter(x=>textOf(x)!=='');const seen=new Set(),items=[],waste=[],quarantine=[],hold=[],nutrients=[];const routes=Object.fromEntries(DESTINATIONS.map(k=>[k,[]]));let inheritedSubstrateStrippedCount=0,nestedEchoAffectedAtoms=0,nestedEchoSuppressedCount=0,routeTagsStripped=0,segmentEchoSuppressedCount=0,delimitedEchoSuppressedCount=0;for(const atom of atoms){const echo=normalizeEcho(textOf(atom),substrates),text=echo.text,key=text.toLowerCase();inheritedSubstrateStrippedCount+=echo.inheritedSubstrateStripped||0;if(echo.nestedSuppressed){nestedEchoAffectedAtoms++;nestedEchoSuppressedCount+=echo.nestedCount;}routeTagsStripped+=echo.routeTagsStripped||0;segmentEchoSuppressedCount+=echo.segmentEchoSuppressed||0;delimitedEchoSuppressedCount+=echo.delimitedEchoSuppressed||0;if(seen.has(key)){const item={...atom,value:text,text,type:'DUPLICATE',status:'EXCRETE',route:'HOLD',priority:0,reason:'duplicate',echoSuppression:echo};waste.push(item);items.push(item);continue;}seen.add(key);const meta=classify(atom,text),item={...atom,value:text,text,...meta,echoSuppression:echo};items.push(item);if(meta.status==='EXCRETE')waste.push(item);else if(meta.status==='QUARANTINE'){quarantine.push(item);routes.HOLD.push(item);}else if(meta.status==='HOLD'){hold.push(item);routes.HOLD.push(item);nutrients.push(item);}else{nutrients.push(item);routes[meta.route].push(item);}}
const ranked=[...nutrients].sort((a,b)=>b.priority-a.priority||a.path.localeCompare(b.path));const summaryItems=selectDiverse(ranked,12);const summary=summaryItems.map(x=>`[${x.type}->${x.route}] ${x.text}`).join(' · ');const counts={};for(const item of items)counts[item.type]=(counts[item.type]||0)+1;return {organ:'GUT',version:'0.2.8',source,mode:'DETERMINISTIC_HEURISTIC_ROUTER',ingested:atoms.length,absorbed:nutrients.length,excreted:waste.length,quarantined:quarantine.length,held:hold.length,typeCounts:counts,routes:Object.fromEntries(Object.entries(routes).map(([k,v])=>[k,{count:v.length,items:v.slice(0,24)}])),nutrients:ranked.slice(0,80),waste:waste.slice(0,80),quarantine:quarantine.slice(0,80),hold:hold.slice(0,80),summary,summaryItemCount:summaryItems.length,antiEcho:{strategy:'INHERITED_SUBSTRATE_SUBTRACTION+PREFIX_DIVERSITY_96+NESTED_ROUTE_TAG_CUTOFF+ROUTE_METADATA_STRIP+ADJACENT_SEGMENT_COLLAPSE+DELIMITED_LONG_SEGMENT_DEDUP',candidateCount:ranked.length,selectedCount:summaryItems.length,suppressedCount:Math.max(0,ranked.length-summaryItems.length),inheritedSubstrateStrippedCount,nestedEchoAffectedAtoms,nestedEchoSuppressedCount,routeTagsStripped,segmentEchoSuppressedCount,delimitedEchoSuppressedCount},boundary:'Deterministic heuristic metabolism only. Exact inherited substrate echoes are contextually subtracted and counted. Repeated long segments inside one atom are deduplicated only across explicit separators (middle dot, semicolon, or newline) and only at 40+ normalized characters, reducing intra-atom metabolic echo without claiming semantic equivalence. JSON-like or heavily escaped structured snippets are classified before lexical contradiction detection and routed back to MUTHER at low priority, preventing incidental words inside engineering artifacts from masquerading as high-priority semantic counterevidence. These rules are auditable heuristics, not semantic truth.'};}
root.GutEngine={digest};
})(typeof window!=='undefined'?window:globalThis);
